// Generated by provision-sitecore-ai-component (manifest: codex-component) — handoff contract for /implement-build-pack.
import type { RichTextField } from '@sitecore-content-sdk/nextjs';
import type { ComponentProps } from 'lib/component-props';

export type CodexComponentFields = {
  copy: RichTextField;
};

export type CodexComponentProps = ComponentProps & {
  fields?: CodexComponentFields;
};
