// Generated by provision-sitecore-ai-component (manifest: general-image-card) — handoff contract for /implement-build-pack.
import type { Field, ImageField, LinkField } from '@sitecore-content-sdk/nextjs';
import type { ComponentProps } from 'lib/component-props';

export type GeneralImageCardFields = {
  generalImageCardImage?: ImageField;
  generalImageCardHeading: Field<string>;
  generalImageCardDescription?: Field<string>;
  generalImageCardLink: LinkField;
};

export type GeneralImageCardProps = ComponentProps & {
  fields?: GeneralImageCardFields;
};
