// Generated by provision-sitecore-ai-component (manifest: general-image-card) — scaffold filled in by /implement-build-pack.
import { Link, NextImage, Text } from '@sitecore-content-sdk/nextjs';
import type { GeneralImageCardProps } from './GeneralImageCard.types';

const GeneralImageCard = (props: GeneralImageCardProps) => {
  const { page, fields } = props;
  const { isEditing } = page.mode;

  if (!fields && !isEditing) {
    return null;
  }

  const { generalImageCardImage, generalImageCardHeading, generalImageCardDescription, generalImageCardLink } = fields ?? {};

  return (
    <div data-component="general-image-card">
      {/* TODO(provision): scaffold only — layout, semantics, and styling come from the Build Pack via /implement-build-pack. */}
      <NextImage editable={isEditing} field={generalImageCardImage} />
      <Text editable={isEditing} field={generalImageCardHeading} />
      <Text editable={isEditing} field={generalImageCardDescription} />
      <Link editable={isEditing} field={generalImageCardLink} />
    </div>
  );
};

export default GeneralImageCard;
