// Generated by provision-sitecore-ai-component (manifest: general-image-card-row) — handoff contract for /implement-build-pack.
import type { Field } from '@sitecore-content-sdk/nextjs';
import type { ComponentProps } from 'lib/component-props';

export type GeneralImageCardRowFields = {
  heading: Field<string>;
};

export type GeneralImageCardRowProps = ComponentProps & {
  fields?: GeneralImageCardRowFields;
};
