// Generated by provision-sitecore-ai-component (manifest: general-image-card-row) — scaffold filled in by /implement-build-pack.
import { AppPlaceholder, Text } from '@sitecore-content-sdk/nextjs';
import componentMap from '.sitecore/component-map';
import type { GeneralImageCardRowProps } from './GeneralImageCardRow.types';

const GeneralImageCardRow = (props: GeneralImageCardRowProps) => {
  const { page, fields } = props;
  const { isEditing } = page.mode;
  const placeholderKey0 = "general-image-cards-" + props.params.DynamicPlaceholderId + "";

  const { heading } = fields ?? {};

  return (
    <div data-component="general-image-card-row">
      {/* TODO(provision): scaffold only — layout, semantics, and styling come from the Build Pack via /implement-build-pack. */}
      <Text editable={isEditing} field={heading} />
      <AppPlaceholder
        name={placeholderKey0}
        rendering={props.rendering}
        page={props.page}
        componentMap={componentMap}
      />
    </div>
  );
};

export default GeneralImageCardRow;
