// Generated by provision-sitecore-ai-component (manifest: rich-text-field) — handoff contract for /implement-build-pack.
import type { RichTextField } from '@sitecore-content-sdk/nextjs';
import type { ComponentProps } from 'lib/component-props';

export type RichTextFieldFields = {
  copy: RichTextField;
};

export type RichTextFieldProps = ComponentProps & {
  fields?: RichTextFieldFields;
};
