// Generated by provision-sitecore-ai-component (manifest: rich-text-field) — scaffold filled in by /implement-build-pack.
import { RichText } from '@sitecore-content-sdk/nextjs';
import type { RichTextFieldProps } from './RichTextField.types';

const RichTextField = (props: RichTextFieldProps) => {
  const { page, fields } = props;
  const { isEditing } = page.mode;

  if (!fields && !isEditing) {
    return null;
  }

  const { copy } = fields ?? {};

  return (
    <div data-component="rich-text-field">
      {/* TODO(provision): scaffold only — layout, semantics, and styling come from the Build Pack via /implement-build-pack. */}
      <RichText className="rtf" editable={isEditing} field={copy} />
    </div>
  );
};

export default RichTextField;
