// Generated by provision-sitecore-ai-component (manifest: image-cta-row) — handoff contract for /implement-build-pack.
import type { Field, ImageField, LinkField } from '@sitecore-content-sdk/nextjs';
import type { ComponentProps } from 'lib/component-props';

export type ImageCtaRowFields = {
  imageCtaRowHeading: Field<string>;
  imageCtaRowBodyText?: Field<string>;
  primaryLink: LinkField;
  // TODO(provision): Checkbox field — markup is design-driven; read the raw value.
  openInModal?: Field<boolean>;
  imageCtaRowImage: ImageField;
  // TODO(provision): Droplist field — stored value is the selected item name; markup is design-driven.
  theme: Field<string>;
  // TODO(provision): Checkbox field — markup is design-driven; read the raw value.
  fullBleedIllustration?: Field<boolean>;
};

export type ImageCtaRowProps = ComponentProps & {
  fields?: ImageCtaRowFields;
};
