// Generated by provision-sitecore-ai-component (manifest: image-cta-row) — scaffold filled in by /implement-build-pack.
import { Link, NextImage, Text } from '@sitecore-content-sdk/nextjs';
import type { ImageCtaRowProps } from './ImageCtaRow.types';

const ImageCtaRow = (props: ImageCtaRowProps) => {
  const { page, fields } = props;
  const { isEditing } = page.mode;

  if (!fields && !isEditing) {
    return null;
  }

  const { imageCtaRowHeading, imageCtaRowBodyText, primaryLink, openInModal, imageCtaRowImage, theme, fullBleedIllustration } = fields ?? {};

  return (
    <div data-component="image-cta-row">
      {/* TODO(provision): scaffold only — layout, semantics, and styling come from the Build Pack via /implement-build-pack. */}
      <Text editable={isEditing} field={imageCtaRowHeading} />
      <Text editable={isEditing} field={imageCtaRowBodyText} />
      <Link editable={isEditing} field={primaryLink} />
      {/* TODO(provision): openInModal — Checkbox field — markup is design-driven; read the raw value. */}
      <NextImage editable={isEditing} field={imageCtaRowImage} />
      {/* TODO(provision): theme — Droplist field — stored value is the selected item name; markup is design-driven. */}
      {/* TODO(provision): fullBleedIllustration — Checkbox field — markup is design-driven; read the raw value. */}
    </div>
  );
};

export default ImageCtaRow;
