// Generated by provision-sitecore-ai-component (manifest: full-width-image-cta-row) — scaffold filled in by /implement-build-pack.
import { Link, NextImage, Text } from '@sitecore-content-sdk/nextjs';
import type { FullWidthImageCtaRowProps } from './FullWidthImageCtaRow.types';

const FullWidthImageCtaRow = (props: FullWidthImageCtaRowProps) => {
  const { page, fields } = props;
  const { isEditing } = page.mode;

  if (!fields && !isEditing) {
    return null;
  }

  const { desktopBackgroundImage, mobileBackgroundImage, heading, copy, primaryLink } = fields ?? {};

  return (
    <div data-component="full-width-image-cta-row">
      {/* TODO(provision): scaffold only — layout, semantics, and styling come from the Build Pack via /implement-build-pack. */}
      <NextImage editable={isEditing} field={desktopBackgroundImage} />
      <NextImage editable={isEditing} field={mobileBackgroundImage} />
      <Text editable={isEditing} field={heading} />
      <Text editable={isEditing} field={copy} />
      <Link editable={isEditing} field={primaryLink} />
    </div>
  );
};

export default FullWidthImageCtaRow;
