// Generated by provision-sitecore-ai-component (manifest: full-width-image-cta-row) — handoff contract for /implement-build-pack.
import type { Field, ImageField, LinkField } from '@sitecore-content-sdk/nextjs';
import type { ComponentProps } from 'lib/component-props';

export type FullWidthImageCtaRowFields = {
  desktopBackgroundImage?: ImageField;
  mobileBackgroundImage?: ImageField;
  heading: Field<string>;
  copy?: Field<string>;
  primaryLink: LinkField;
};

export type FullWidthImageCtaRowProps = ComponentProps & {
  fields?: FullWidthImageCtaRowFields;
};
